name: base_mvvm_cubit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  go_router: ^14.2.1
  intl: ^0.18.0
  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  shared_preferences: ^2.2.3
  curl_logger_dio_interceptor: ^1.0.0
  easy_localization: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.6.0
  retrofit_generator: ^8.1.2
  json_serializable:
  intl_utils:



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
